config/routes.rb
Rails.application.routes.draw do
  resources :horses

end

app/models/horse.rb
class Horse < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :set_horse, only: [:show, :edit, :update, :destroy]

  # GET /horses
  # GET /horses.json
  def index
    @horses = Horse.all
  end

  # GET /horses/1
  # GET /horses/1.json
  def show
  end

  # GET /horses/new
  def new
    @horse = Horse.new
  end

  # GET /horses/1/edit
  def edit
  end

  # POST /horses
  # POST /horses.json
  def create
    @horse = Horse.new(horse_params)

    respond_to do |format|
      if @horse.save
        format.html { redirect_to @horse, notice: 'Horse was successfully created.' }
        format.json { render :show, status: :created, location: @horse }
      else
        format.html { render :new }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horses/1
  # PATCH/PUT /horses/1.json
  def update
    horse = Horse.find(params[:id])
    puts params
    if params[:_method] =="patch"
      horse.update_attributes(horse_params)
      redirect_to horse
    else
      if horse.update_attributes(horsey_params)
        redirect_to horse
      else
        render :edit
      end
    end
  end

  # DELETE /horses/1
  # DELETE /horses/1.json
  def destroy
    @horse.destroy
    respond_to do |format|
      format.html { redirect_to horses_url, notice: 'Horse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horse
      @horse = Horse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def horse_params
      params.require(:horse).permit(:name, :breed)
    end

    def horsey_params
      params.permit(:horse, :name, :can_escape, :breed, :id)
    end
end

# <form id="rule-world" action="/horses/1?can_escape=1&amp;name=Berni&amp;breed=budweiser" method="POST">
#   <input type="hidden" name="_method" value="put">
# <input type="submit" value="rule world">
# </form>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/views/horses/_form.html.erb
<%= form_for(@horse) do |f| %>
  <% if @horse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
      <% @horse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/horses/edit.html.erb
<div class="centered">
<h1>Editing Horse</h1>

<%= render 'form' %>

<%= link_to 'Show', @horse %> |
<%= link_to 'Back', horses_path %>
</div>

app/views/horses/index.html.erb
<p id="notice"><%= notice %></p>
<div class="centered">
<h1>Listing Horses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Can escape</th>
      <th>Breed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @horses.each do |horse| %>
      <tr>
        <td><%= horse.name %></td>
        <td><%= horse.can_escape %></td>
        <td><%= horse.breed %></td>
        <td><%= link_to 'Show', horse %></td>
        <td><%= link_to 'Edit', edit_horse_path(horse) %></td>
        <td><%= link_to 'Destroy', horse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Horse', new_horse_path %>
</div>

app/views/horses/new.html.erb
<div class="centered">

<h1>New Horse</h1>

<%= render 'form' %>

<%= link_to 'Back', horses_path %>
</div>

app/views/horses/show.html.erb
<div class="centered">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @horse.name %>
</p>

<p>
  <strong>Can escape:</strong>
  <%= @horse.can_escape %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @horse.breed %>
</p>

<%= link_to 'Edit', edit_horse_path(@horse) %> |
<%= link_to 'Back', horses_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HorseManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>